name: poetry_stream
description: "Meditativní stream české poezie"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  go_router: ^14.8.1
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  google_fonts: ^6.2.1
  uuid: ^4.5.1
  yaml: ^3.1.3
  in_app_purchase: ^3.2.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.jpg"
  web:
    generate: true
    image_path: "assets/icon.jpg"
  windows:
    generate: true
    image_path: "assets/icon.jpg"
  macos:
    generate: true
    image_path: "assets/icon.jpg"

flutter:
  uses-material-design: true

  assets:
    - assets/poems/
