- title: Máj
  text: |
    Byl pozdní večer, první máj,
    večerní máj, byl lásky čas.
    Hrdliččin zval ku lásce hlas,
    kde borový zaváněl háj.

- title: Zlaté struny
  text: |
    Kdo v zlaté struny zahrát zná,
    ten ztracen jest i jiným světům;
    neb hudba jest ta rajská brána,
    kudy se vchází nebem k květům.

- title: Nad vodou
  text: |
    Nad vodou strom se vážně kloní,
    a v trávě leží tichý stín.
    Kdes ve tmě slavík zpívá, zvoní,
    jak flétna z hvězdných dálek, klín.

- title: Ticho v lese
  text: |
    Ticho je v lese, ticho všude,
    jak v kostele, když kněz se modlí.
    Jen potok šumí, šepce, bude
    si hrát, než zima přijde podlí.

- title: Podzimní listí
  text: |
    Podzimní listí padá tiše,
    zlacené stopy na zemi.
    Vítr si šeptá, nikdo slyší,
    jak čas se ztrácí s okamžiky.

- title: Měsíc
  text: |
    Měsíc se dívá přes okno,
    stříbrné světlo na podlaze.
    Všechno je tiché, všechno pokojno,
    jak sen, co nikdo nevymaže.

- title: Ráno
  text: |
    Ráno se budí, rosa třpytí,
    na stéblech trávy diamanty.
    Svět je tak krásný, stojí za žití,
    když slunce zlacuje ty instranty.

- title: V dálce
  text: |
    V dálce se modrá hora zvedá,
    oblaka tančí na obzoru.
    Duše má touží, srdce hledá
    cestu zpět k dávnému hovoru.
