- title: Moje poznámky
  text: |
    3. října 2023, 9:42
    příkrost života
    a party satanášů
    popíjejí rozum
    zhaslo tam kde měla klín
    pohádkový mlýn

    zebe mě jistota
    že mi všichni zemřou
    nebo já jim uteču
    do jejich vlastních slz

    Lady Diana zpívá madrigaly
    nekrofilní pičus
    zalévá meruňky
    penis si myje v heřmánku
    umřel jsi pro nás Beránku

    3. října 2023, 9:30
    vše je jen zelený zodiak
    vše jest jen hovnem
    šelestem v podpaží
    dekoltem tlusté báby
    vše je jen zelený zodiak
    a přichází Král Slávy

    2. října 2023, 20:15
    je jedno s kým šukáš
    záleží na jediném
    a to aby tvůj partner/ka
    tento děj brali jako hru
    vášnivou hru obdarování
    vem si mě - to je napsáno nad branou do nebes
    na balóncích od sazí černých
    jako tvé ochlupení
    vem si mě
    chci si s tebou hrát
    a zažívat to
    že víš
    že máš svou cenu
    ještě dnes se mnou budeš v ráji

    2. října 2023, 20:12
    jediný zákon
    který platí v celém vesmíru
    je:
    píča rodí píču

    2. října 2023, 10:35
    nepamatuji si zhola nic
    jestli to takhle půjde dál
    nastoupím do Bohnic
    spustím svůj recitál
    já velký generál
    okupovat budu tvojí píče
    areál
    když si tě stvořím
    však teď ještě nehoří

    2. října 2023, 10:18
    rybovraník kulhá
    pokulhává
    to je moje žlutá zpráva

    anekdoty chybí
    vraník nebo ryby?
    kosatky v jícnu hologramu
    váží pět gramů

    hlavolam a hladomor
    krysy se množí sršni rojí
    máme svoje "Oni!"
    kyselá srdce
    v kolejištích zpráv

    maměnka s děckem
    a poplach návratů
    co zbyde na tátu?
    ach brokátové cihly
    cihly z brokátu
    kolem se mihly

    a zatravněná radost
    je šperkovnicí ctnosti
    pro budoucnost minulosti
    když klepe na střechu
    rodinného "Domů!"
  
- title: Slzy
  text: |
    někde
    kde nikoho nebudou hodnotit
    kde každý každému ponechá jeho sen
    jeho projev lásky
    nechutná ti?
    fajn zkus to jinde

    a všechny bytosti naleznou svou jedinečnost
    kterou manifestují Stvořitele
    a budou si ji chránit
    a pomáhat ostatním chránit tu jejich
    to co jim nikdo nesmí vzít

    jsme děti
    a dětmi zůstaneme
    o co jsi povyrostl Čeňku?
    jen o deficit snu a lásky
    buď dítě
    neusmívej se když nemáš proč
    a plač když když to na tebe přijde

    dvacet let jsem neplakal
    až teď 20. prosince ráno
    protože se mi vrátilo dětství
    jehož je štěstí podstatou

    štěstí bez formy a bez obsahu
    bez krásy bez berliček
    s naprostou nesmyslností sdílení
    bez primitivních vágních hysterií
    naprostá nenucenost
    naprostost

    a tak ti nebudu vyprávět
    co je za sedmero horami
    miluj mě pokud můžeš
    a pokud ne řekni mi to
    ať si nebereme sny
    a neplýtváme láskou

    měj na paměti hloubku
    niternou pravdu tvého zámku

    toto je antibáseň
    je naprosto bez ambicí
    nic po tobě nechce
    a ty si na ní nic nevezmeš
    jen to
    že můžeš odejít svobodný