- title: "PRAVDU MÁ JEN JEDEN ANEB V ZORNÉM POLI MINISTERSTVA LÁSKY: od kořene penisu až po chodidla"
  text: |
    od kořene penisu až po chodidla
    vražda na tři hroby
    jemu to prochází
    jemu to chodí
    dovi

    a přece zbývá matný šat vyrážky
    zázněje pigmentu
    sněhem přikrytá pole
    tolik je veršů kolem
    a tolik nenasytných jar

    nechte je prosím spát - ty tři
    v rozmarýnovém opojení
    kol světlo či to věčný svit?
    kol lišky mydlářky

    s frekvencí goril na talířích
    vyhlášených restaurací
    na těsných okrajích pasek
    valašských velkoskladů dřeva

    nechte je spát
    nechte je prosím
    protože není nikoho
    kdo by se o ně postaral

- title: "PRAVDU MÁ JEN JEDEN: čmeláci mají stříbrná varlata"
  text: |
    čmeláci mají stříbrná varlata
    déšť z kříže je leští
    a naděláno do bláta
    a ukazováček na troleji štěstí
    a - a
    zvoní jiřičky s placentou hřiven
    uvidíme co na to velryby
    s bílými kly obtěžují rozum tekoucí jak moč do plenek
    ach ta inkontinence života
    kořeněná ibiškem

- title: "PRAVDU MÁ JEN JEDEN: v hledáčku peristaltik moderní doby"
  text: |
    v hledáčku peristaltik moderní doby
    žalostně plujeme korábem s kolečky
    mezery jsou všude
    za i před námi
    vedle nás
    a do těch váz se střílí
    těch nezřízených váz
    a v přebytečných žlázách kvete listí

- title: "PRAVDU MÁ JEN JEDEN: do ptačích sborů"
  text: |
    do ptačích sborů,
    ještě hloub,
    tu na ulici leží kloub
    jak vyvřelina minulosti
    jak hostina na svátku hostí

    jen jeden mág
    jen jedna dcera
    se milují
    hle zpodvečera se nikl odpařuje
    jsme láskou
    vítr duch se štítí hříchu vstoje
    těsnice brání uzdravení
    a vzdát se nabytého jmění?

    cizojakost a víry blamáž
    je toho dost
    je toho až až
    a doma nejsi vítaný
    vždyť odumřelo všecičko
    ach bohorodá matičko
    kam?

    šíje a universum
    dvě slova jež nás vábí
    idiocie a zakalená řeka
    co slouží špíně nadčlověka
    a mír se líně převaluje
    v násilí

    to oni! oni zasili!
    Bože!
    sklípkan pekla rozhodl se
    že nespálí se letmým brusem
    jde níž a níže
    v rozkroku se zastaví
    čenichá a líže

    je vytyčena cesta
    jiřiny kvetou
    a jeden ze sta
    končí větou:
    jubilate Deo omnis terra
    slyšíš je růst
    slyšíš je růst
    jako když zlomená
    končetina srůstá

    dej písni ústa Boženy
    navštivte pustá lože
    v nich výdrž jistotu
    a to co vede nemilosrdně
    k životu

- title: "PRAVDU MÁ JEN JEDEN: Nahota"
  text: |
    vnímaje tvou nahotu
    začínám rozumět
    miluji každou faldu
    každý převis
    Čínskou zeď

    miluji to nikdy - teď
    nahota není tvým tělem
    nahota je postoj
    k přirozenému podpaží
    ochlupené p..i
    ztuhlým bradavkám
    šikovnému jazyku a retům majetnickým
    a kořistným
    skrze tvou nahotu vnímám
    a poznávám sebe

    proto se svlékám a sdílím se s tebou
    nahota je dar
    jež funguje
    když přichází zrníčko po zrníčku
    jako sůl
    když přichází jako koření
    coby dar vzácný a ultimátní

    Ježíš to už jednou udělal
    šlus
    nahota je v tom stejná
    s každým stykem se musíš stát dítětem
    které nezná minulost
    velký konžský most
    až k delíriu bdělosti

    tvá nahoto
    jsi bdělá jako květ
    odzbrojující jak katetr internistky
    lišíš se tím
    že nejsi náhražkou ale přepychem
    v časech
    kdy nahý Kristus rozhazuje letáky

- title: "PRAVDU MÁ JEN JEDEN: a mnoho kazivců zůstalo na penisu"
  text: |
    a mnoho kazivců zůstalo na penisu
    a blouznění a spásy
    a modrý samuraj
    dosedl na zem jako sníh
    dírky se vstřebaly
    jak poražená Argentina
    jak motýl lišaj zvaný Smrtihlav

- title: "PRAVDU MÁ JEN JEDEN: promiskuitní dobrozlo"
  text: |
    promiskuitní dobrozlo
    všude
    přítomnost příběhu
    anexe jejího srdce

- title: "PRAVDU MÁ JEN JEDEN: Zoneta aneb O dívce"
  text: |
    luštila křížovky a dekadentně spala
    sama

    většinou sama i když - kdoví?
    zajímavě močila

    sedala si na mísu jako na trůn
    začala zpívat a vydávat rozkazy
    do toho čůrek čůrek čůrek

    leštila si rtíky o mráz dnešků
    tančila v teplákách a - rakovině se smála
    v klíně kvetla jak astry macešky a tulipány
    udržovala vláhu pro ztopořená pohlaví

    vlastně ano
    věčně s někým spala
    byla celá svoje
    zohavená budoucností
    standardním metrem pro metrosexuály
    jasná přítelkyně větru
    a legenda z Šesté Mojžíšovy

    nečekala na sebe ale děla se
    nikdy se nestyděla
    za nic a za nikoho
    uvázala psovi kolem hlavy žlutofialovou pentli
    a poslouchala jazz

    všichni stavěli domy a kupovaly byty
    ale ona volila život v chatrči
    jenom ona a pár vyvolených z knihy Jozue

    praskaka ve švech svých myšlenek
    odevzdávala se koním
    milovala koně
    míchala jablka s hruškami
    a vůbec jí to nevadilo
    možná byla trochu přihřátá
    ale co na tom záleží?

    princezna neurotiků
    geografka inteligence
    plačící mýtina
    nikdy se necítila nemístně
    a straky jí zobali z ruky

    převinula osud
    a hází stíny do tmy
    neurvale a laicky
    je jako strom bez kořenů
    jako slunce bez erupcí
    zrzka bez pih
    celá odeštivá
    v přítmí infarktových stavů
    Zoneta - dívka trosečník

- title: "PRAVDU MÁ JEN JEDEN: byl jsem dnes u fyzioterapeutky"
  text: |
    byl jsem dnes u fyzioterapeutky
    to bylo baroko
    to byl Súdán
    mikrotenové myšlenky
    a těla co by mohla
    vzpomínka se ukázalasvléklaseaodcupitala
    hele M., stačíkdyšmědáš d o k up y
    s t a č í k d y ž m r d á š dokupy
    ano nestačí že mi dáš
    protože nemám čím platit
    dlužím i samotnému Bohu
    a nejvíc sobě
    no tak snad proto bys mohla
    ztratit vše pro můj kříž
    však ze své vlastní vůle

- title: "PRAVDU MÁ JEN JEDEN: tu skladbu pro hornu a klavír napsal Studňa pro Kaminského"
  text: |
    tu skladbu pro hornu a klavír napsal Studňa pro Kaminského
    klavír jsem zastal já
    dostal jsem tehdy v Uničově diplom za nejlepší korepetici či co
    no měl jsem při přebírání té fangle koženou bundu
    no oni lidi do jistého věku nosí koženou bundu
    teď už nenosím koženou bundu
    vzpomínám na to

    a taky na počátky svý duševní nemoci
    psychiatričce v Ostravě tehdy padalo ramínko
    a ještě si rád zavzpomínám na ostravský holky
    ono vůbec v Ově bylo fajn
    zažil jsem ji v přerodu
    a když jsem čekal na šalinu
    měl jsem divný pocity
    který si teď jasně vybavuju
    chtěl jsem jí onehdá dát pusu na ucho
    ale nedal

    a starý Zenkl nám s jednou cérkou v Hodoníně v lázních opatřil oběd a zmrzlinový pohár
    když jsme si za ním přijeli pro zápočet
    a jeden můj spolužák dělá ředitele ZUŠ
    a já se nemohu zbavit pocitu
    že mě za cosi už dvacet let trestá
    ale vím že Bůh není ten
    který mu našeptává
    sper to ďas
    
    a Kaminski dnes troubí v Číně
    protože politika ho nezajímá
    a já polehávám na kanapi
    což je téměř to samé
    ta skladba se jmenovala Arietta

- title: "PRAVDU MÁ JEN JEDEN: nějak si přestávám vážit andělů"
  text: |
    nějak si přestávám vážit andělů
    hrkám slovy
    a plaše típám rozbušky zdraví a nemocí
    jsem v inteligentním presu
    nákup nemám
    drancovali v shopu U pilníků
    dráždili ji
    věděl jsem že nechce
    ale co naplat
    byli to andělé
    asi dnes nakoupím jinde

- title: "PRAVDU MÁ JEN JEDEN: tolik je bílých situací"
  text: |
    tolik je bílých situací
    tolik je moří moří v ptácích
    a toho vzlyku shora zdola
    mračí se modla deskulptura

    u pultu žabec černý celý
    ach co mi PB nenadělí
    hořící moře v krajce její
    zmizely šaty zbyl jen vějíř

    jen tělo ústa zahalená
    a sobi v tlamách samá pěna
    a děti křičí Santa Santa
    a svatí močí do bažanta

    bílý je sníh a v loži mrazí
    láskou se nikdo nenakazí
    když zevnitř nejde trhej růže
    v stínohře náměsíčných tužeb

- title: "PRAVDU MÁ JEN JEDEN: na kafi s Hospodinem"
  text: |
    na kafi s Hospodinem
    přemýšlím o sobě
    a není to věru
    veselé přemýšlení
    utéct tak od sebe
    tam onde ku prameni
    k jinačí podobě
    a odpovídám rýmem
